language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3
    - otp_release: 19.3
      elixir: 1.3
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.0
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.5
notifications:
  recipients:
    - eduardo@gurgel.me
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, coveralls.travis"
after_script:
  - "MIX_ENV=docs mix do deps.get, inch.report"
