language: elixir
elixir:
  - 1.0.0
  - 1.1.1
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - 18.2
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, coveralls.travis"
after_script:
  - "MIX_ENV=docs mix do deps.get, inch.report"
